name: ci-cd-python.yml
on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
        
    inputs:
      runTests:
        required: false
        type: boolean
        default: false
      performRelease:
        required: false
        type: boolean
        default: false

env:
  IMAGE_NAME_MIXED_CASE: "${{ github.repository }}"

jobs:
  build-check-test-push:
    name: Build, check, test, push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: 'true'
          fetch-depth: 2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code formatting
        run: |
          ruff check .
          ruff format --check

      - name: Run tests
        if: ${{ inputs.runTests }}
        run: pytest --junitxml=test-results.xml

      - name: Check if perform release
        id: perform_release
        run: |
          PERFORM_RELEASE=false
          if [[ "${GITHUB_REF}" == "refs/heads/main" || "${GITHUB_REF}" == "refs/heads/develop" || "${GITHUB_REF}" == "refs/heads/aks-dev" ]]; then
            PERFORM_RELEASE=true
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            PERFORM_RELEASE=true
          elif [[ "${{ inputs.performRelease }}" == "true" ]]; then
            PERFORM_RELEASE=true
          fi
          echo "PERFORM_RELEASE=${PERFORM_RELEASE}" >> $GITHUB_ENV
          echo "Perform release: ${PERFORM_RELEASE}"

      - name: Lowercase Docker Image Name
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME_MIXED_CASE,,}" >> "${GITHUB_ENV}"

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: 'false'
          tags: 'hsldevcom/${{ env.IMAGE_NAME }}:${{ github.sha }}'

      - name: Setup Docker Buildx
        if: env.PERFORM_RELEASE == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        if: env.PERFORM_RELEASE == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.vendor=hsldevcom

      - name: Login to Docker Hub
        if: env.PERFORM_RELEASE == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        if: env.PERFORM_RELEASE == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ env.PERFORM_RELEASE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
