name: ci-cd-java.yml

permissions:
  contents: read
  packages: read

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    inputs:
      # it is required for backwards compatibility with CI/CD pipelines that have not been yet fully migrated to shared workflows
      uploadJarArtifact:
        required: false
        type: boolean
        default: false
      jarArtifactName:
        required: false
        type: string
      jarArtifactPath:
        required: false
        type: string
      performRelease:
        required: false
        type: boolean
        default: false
      workingDirectory:
        required: false
        type: string
        default: .
      imageName:
        required: false
        type: string
      runTestsInsideDocker:
        required: false
        type: boolean
        default: false

env:
  IMAGE_NAME_MIXED_CASE: "${{ github.repository }}"
  TEST_STAGE: test

jobs:
  build-check-test-push:
    name: Build, check, test, push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: 'true'
          fetch-depth: 2

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Check code format and lint
        working-directory: ${{ inputs.workingDirectory }}
        run: |
          mvn spotless:check

      - name: Run tests outside Docker
        working-directory: ${{ inputs.workingDirectory }}
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Integration tests (Testcontainers)
        working-directory: ${{ inputs.workingDirectory }}
        run: mvn verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build artifact
        working-directory: ${{ inputs.workingDirectory }}
        run: mvn package -Dmaven.test.skip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .jar artifact
        if: ${{ inputs.uploadJarArtifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.jarArtifactName }}
          path: ${{ inputs.jarArtifactPath }}

      - name: Set Docker Image Name
        run: |
          OWNER="${GITHUB_REPOSITORY%%/*}"

          if [[ -n "${{ inputs.imageName }}" ]]; then
            IMAGE_NAME="${OWNER,,}/${{ inputs.imageName }}"
          else
            IMAGE_NAME="${GITHUB_REPOSITORY,,}"
          fi

          echo "IMAGE_NAME=${IMAGE_NAME}" >> "$GITHUB_ENV"

      - name: Build & run tests inside Docker
        if: ${{ inputs.runTestsInsideDocker }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.workingDirectory }}
          load: true
          target: "${{ env.TEST_STAGE }}"
          tags: "${{ env.IMAGE_NAME }}:${{ env.TEST_STAGE }}"
          secrets:
            github_token=${{ secrets.GITHUB_TOKEN }}
          build-args:
            GITHUB_ACTOR=${{ github.actor }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.workingDirectory }}
          push: 'false'
          tags: 'hsldevcom/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          build-args:
            GITHUB_ACTOR=${{ github.actor }}

      - name: Check if perform release
        id: perform_release
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" || "${GITHUB_REF}" == "refs/heads/develop" || "${GITHUB_REF}" == "refs/heads/aks-dev" ]]; then
            echo "PERFORM_RELEASE=true" >> $GITHUB_ENV
          elif [[ "${{ inputs.performRelease }}" == "true" ]]; then
            echo "PERFORM_RELEASE=true" >> $GITHUB_ENV
          else
            echo "PERFORM_RELEASE=false" >> $GITHUB_ENV
          fi
            echo "Perform release condition: PERFORM_RELEASE"

      - name: Extract Docker metadata
        if: ${{ env.PERFORM_RELEASE == 'true' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.vendor=hsldevcom

      - name: Setup Docker Buildx
        if: ${{ env.PERFORM_RELEASE == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        if: ${{ env.PERFORM_RELEASE == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        if: ${{ env.PERFORM_RELEASE == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.workingDirectory }}
          push: ${{ env.PERFORM_RELEASE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}